name: Acción de Autohospedado
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Hacer git clone
        run: |
          cd C:\Users\Administrador\Documents
          $fecha = Get-Date
          $fechaString = $fecha.ToString()
          $fechafinal = $fechaString.Replace(" ", "-").Replace(":", "-").Replace("/","-")
          mkdir $fechafinal
          cd $fechafinal
          git clone https://github.com/AnthonyMonsalve/NetFramework35.git
          cd NetFramework35

          $fileContent = Get-Content -Path "C:\Users\Administrador\Documents\$fechafinal\NetFramework35\Default.aspx"
          $fileContent = $fileContent -replace "#fff", "red"
          $fileContent | Set-Content -Path "C:\Users\Administrador\Documents\$fechafinal\NetFramework35\Default.aspx"

          
          msbuild /t:Build /p:Configuracion=Release

          $dirActual = $PWD.path
          
          if (Test-Path -Path "C:\inetpub\wwwroot\TestIIS\bin") {
              Remove-Item -Path "C:\inetpub\wwwroot\TestIIS\bin" -Recurse
          }
          Copy-Item -Path "$dirActual\bin" -Destination "C:\inetpub\wwwroot\TestIIS" -Recurse

          Get-ChildItem -Path "C:\inetpub\wwwroot\TestIIS" -Filter "*.aspx" | Remove-Item -Force
          Copy-Item -Path "$dirActual\*.aspx" -Destination "C:\inetpub\wwwroot\TestIIS" -Recurse
